name: Build APK with Custom App Name

on:
  workflow_dispatch:
    inputs:
      user_id:
        description: 'User ID'
        required: true
      app_name:
        description: 'Custom App Name'
        required: true
             

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Replace App Name in strings.xml
        run: |
          sed -i "s|Web2App|${{ github.event.inputs.app_name }}|g" app/src/main/res/values/strings.xml

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-${{ github.event.inputs.user_id }}
          path: app/build/outputs/apk/debug/app-debug.apk
