name: Build APK with Custom App Name

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'App Name'
        required: true
      app_url:
        description: 'Website URL'
        required: true
      request_id:
        description: 'Unique Request ID'
        required: true
      package_name:
        description: 'Package Name'
        required: true            
      icon_url:
        description: 'URL for App Icon'
        required: true        

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ImageMagick
        run: sudo apt-get install -y imagemagick

      - name: Download user icon
        run: wget -O user_icon.png ${{ github.event.inputs.icon_url }}

      - name: Resize and replace app icons
        run: |
          ICON_DIR=app/src/main/res
          convert user_icon.png -resize 48x48     $ICON_DIR/mipmap-mdpi/ic_launcher.png
          convert user_icon.png -resize 72x72     $ICON_DIR/mipmap-hdpi/ic_launcher.png
          convert user_icon.png -resize 96x96     $ICON_DIR/mipmap-xhdpi/ic_launcher.png
          convert user_icon.png -resize 144x144   $ICON_DIR/mipmap-xxhdpi/ic_launcher.png
          convert user_icon.png -resize 192x192   $ICON_DIR/mipmap-xxxhdpi/ic_launcher.png        
          convert user_icon.png -resize 48x48     $ICON_DIR/mipmap-mdpi/ic_launcher_round.png
          convert user_icon.png -resize 72x72     $ICON_DIR/mipmap-hdpi/ic_launcher_round.png
          convert user_icon.png -resize 96x96     $ICON_DIR/mipmap-xhdpi/ic_launcher_round.png
          convert user_icon.png -resize 144x144   $ICON_DIR/mipmap-xxhdpi/ic_launcher_round.png
          convert user_icon.png -resize 192x192   $ICON_DIR/mipmap-xxxhdpi/ic_launcher_round.png       
          convert user_icon.png -resize 48x48     $ICON_DIR/mipmap-mdpi/ic_launcher_foreground.png
          convert user_icon.png -resize 72x72     $ICON_DIR/mipmap-hdpi/ic_launcher_foreground.png
          convert user_icon.png -resize 96x96     $ICON_DIR/mipmap-xhdpi/ic_launcher_foreground.png
          convert user_icon.png -resize 144x144   $ICON_DIR/mipmap-xxhdpi/ic_launcher_foreground.png
          convert user_icon.png -resize 192x192   $ICON_DIR/mipmap-xxxhdpi/ic_launcher_foreground.png              
          convert user_icon.png -resize 48x48     $ICON_DIR/mipmap-mdpi/ic_launcher_background.png
          convert user_icon.png -resize 72x72     $ICON_DIR/mipmap-hdpi/ic_launcher_background.png
          convert user_icon.png -resize 96x96     $ICON_DIR/mipmap-xhdpi/ic_launcher_background.png
          convert user_icon.png -resize 144x144   $ICON_DIR/mipmap-xxhdpi/ic_launcher_background.png
          convert user_icon.png -resize 192x192   $ICON_DIR/mipmap-xxxhdpi/ic_launcher_background.png              

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Replace App Name in strings.xml
        run: |
          sed -i "s|APP_NAME_PLACEHOLDER|${{ github.event.inputs.app_name }}|g" app/src/main/res/values/strings.xml
          sed -i "s|URL_PLACEHOLDER|${{ github.event.inputs.app_url }}|g" app/src/main/res/values/strings.xml
          sed -i 's|applicationId = "com.app.web2app"|applicationId = "com.app.emagapp"|' app/build.gradle.kts

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.request_id }}-apk
          path: app/build/outputs/apk/debug/app-debug.apk
