name: Build APK with Custom App Name

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'App Name'
        required: true
      app_url:
        description: 'Website URL'
        required: true
      request_id:
        description: 'Unique Request ID'
        required: true
             

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Replace App Name in strings.xml
        run: |
          sed -i "s|APP_NAME_PLACEHOLDER|${{ github.event.inputs.app_name }}|g" app/src/main/res/values/strings.xml
          sed -i "s|URL_PLACEHOLDER|${{ github.event.inputs.app_url }}|g" app/src/main/res/values/strings.xml

      - name: Build APK
        run: ./gradlew assembleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.request_id }}-apk
          path: app/build/outputs/apk/release/app-release.apk
